// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Diagnostics;
using System.Drawing;
using Microsoft.VisualBasic;

namespace WindowsApp6.My.Resources
{

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("WindowsApp6.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _4981_2
        {
            get
            {
                var obj = ResourceManager.GetObject("4981-2", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adb
        {
            get
            {
                var obj = ResourceManager.GetObject("adb", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AdbWinApi
        {
            get
            {
                var obj = ResourceManager.GetObject("AdbWinApi", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Batman_Wallpapers_For_Phone_008
        {
            get
            {
                var obj = ResourceManager.GetObject("Batman-Wallpapers-For-Phone-008", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProgramFiles
        {
            get
            {
                var obj = ResourceManager.GetObject("ProgramFiles", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Windows32
        {
            get
            {
                var obj = ResourceManager.GetObject("Windows32", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xtreme
        {
            get
            {
                var obj = ResourceManager.GetObject("xtreme", resourceCulture);
                return (byte[])obj;
            }
        }
    }
}